### PR TITLE
Moved package to com.graphhopper

### LINKED ISSUE #40: package io.swagger should be com.graphhopper for Geocoding API

### PR DESCRIPTION
**Pull request by boldtrn**
Fixes #40 

This PR changed the package name of the geocoding client.

I changed it to: `invokerPackage": "com.graphhopper.geocoding-client`
Swagger replaces - with _, so maybe we should just call it geocoding or the 'fullname' `directions-api-java-client-geocoding`?

What do you think?

BTW: I also included the fix of #41, so maybe we just close #41?

BTW2: Something that I find a bit weird is that when I run `mvn clean test verify` the tests block appears twice, but I am not sure if this is a local bug or even an issue at atll:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Concurrency config is parallel='methods', perCoreThreadCount=true, threadCount=2, useUnlimitedThreads=false
Running com.graphhopper.geocoding_client.api.GeocodingApiTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.372 sec
```

### CODE REVIEW

**Comment by karussell** [comment]
For the route optimization I've picked a separated package "routeopt/client" instead of the "`-`"

The BTW2 seems strange, but I made the observation that no verify is necessary anymore, also for graphhopper to run the integration tests. Maybe here too?

> BTW: I also included the fix of #41, so maybe we just close #41?

Sorry, saw this too late and already merged it

**Comment by karussell** [comment]
It is "routeopt/client/api"

**Comment by boldtrn** [comment]
Thanks I updated the GeoCoding client package. This looks good now. However the test block still appears twice.

> Sorry, saw this too late and already merged it

No problem, will merge the master :).

**Comment by karussell** [comment]
Thanks - feel free to merge it!

> However the test block still appears twice.

Some issue in the autogenerated pom I guess ... nothing important I think

**Pull request merged**
