### PR TITLE
Added Travis.yml

### PR DESCRIPTION
**Pull request by boldtrn**
I added a travis.yml file to enable CI for the Client. I think we need to enable CI builds for this repo in travis. I tested it for my fork and it worked.

### CODE REVIEW

**Comment by karussell** [comment]
Thanks!

**Comment by karussell** [comment]
It is now running here: https://travis-ci.org/graphhopper/directions-api-java-client

**Comment by devemux86** [comment]
The key will stay visible?

**Comment by karussell** [comment]
We can hide it via: https://docs.travis-ci.com/user/encryption-keys/ but not sure if this is important (?)

**Pull request merged**
