### PR TITLE
Added osm key

### LINKED ISSUE #48: Geocoding: Add osm_key
Currently the Geocoding client does not parse the field `osm_key`.

### PR DESCRIPTION
**Pull request by boldtrn**
This fixes #48. I also added the geocoding tests again, as they seem to have been lost with the latest generation. It's a bit annoying that Swagger generates new timestamps in every file, so we have a lot of unnecessary changes.

### CODE REVIEW

**Comment by boldtrn** [comment]
I added some more tests. I wrote them for an earlier version of the client to test if it works. I figured small tests might be better than no tests ;). In the end we should have a couple of better tests.

**Comment by karussell** [comment]
> I added some more tests.

Cool, thanks - sorry for removing them! Maybe we put the tests in the examples module? This way we can easier overwrite the client directory.

**Comment by karussell** [comment]
> It's a bit annoying that Swagger generates new timestamps in every file

I found this: https://github.com/swagger-api/swagger-codegen/issues/2834 ... will look if `config-help` helps us

**Comment by karussell** [comment]
That was easy: https://github.com/graphhopper/directions-api-clients/commit/500e187c2f3371c81c7186b52259b6ce7a56263e

**Comment by boldtrn** [comment]
> Cool, thanks - sorry for removing them!

No worries :).

> Maybe we put the tests in the examples module?

Yes you are right, we could probably do this. Should I add this to this PR or once this is merged?

**Comment by boldtrn** [comment]
> That was easy

Nice :)

**Comment by boldtrn** [comment]
Any updates on this? Should I merge this or change something?

**Comment by karussell** [comment]
Would you mind to remove the dates? (so that we have now many changes but next time less)

> Should I add this to this PR or once this is merged?

a separate would be nice

**Comment by boldtrn** [comment]
> Would you mind to remove the dates? (so that we have now many changes but next time less)

I just removed the dates and the tests. I will add the tests, once this PR is merged.

**Comment by karussell** [comment]
Thanks!

**Pull request merged**
