### PR TITLE
refactor create request

### PR DESCRIPTION
**Pull request by oblonski**

### CODE REVIEW

**Comment by oblonski** [comment]
IT test failed, since no key from system property is provided. How can I set the key?

tmpInstruction, tmpElevation is calculated twice here. However, I find it easier to do this here rather than elsewhere.

**Comment by karussell** [comment]
see the readme ;)
`mvn -Dgraphhopper.key=[YOUR_KEY] clean test verify`

**Comment by karussell** [comment]
BTW: thanks!

**Comment by karussell** [comment]
new version will be deployed soon, will re-add the in-sync request

**Pull request merged**
