### PR TITLE
Add exceptions

### PR DESCRIPTION
**Pull request by boldtrn**
I added parsing for the two new Exceptions of GH. Currently the API returns `not_found_point_index` instead of `point_index` we have to changes this, once the API is updated :).

Also I was not able to produce an out of bounds exception, not sure if this is not included in the API right now?

### CODE REVIEW

**Comment by karussell** [comment]
Not yet updated in the API, yes. Will do this very soon.

**Comment by boldtrn** [comment]
> Not yet updated in the API, yes. Will do this very soon.

Ok, should we wait with merging until the API is updated?

**Comment by karussell** [comment]
Probably, but again will try to make this happening this week.

**Comment by karussell** [comment]
Should be updated tomorrow (motor vehicles are already up to date).

**Comment by boldtrn** [comment]
> Should be updated tomorrow

Ok, I updated my PR and added a test for the Point out of Bounds exception.

**Comment by karussell** [comment]
Thanks!

**Pull request merged**
