### PR TITLE
Added the sonatype repo to the pom

### PR DESCRIPTION
**Pull request by boldtrn**
Not sure if I should add it to the super pom. I thought it would be better in the super pom. On the other hand we would keep the impact as small as possible.

### CODE REVIEW

**Comment by karussell** [comment]
Hmmh, not sure when you tried this snapshot related thing. But I was moving most of the repos to the new deployment structure. E.g. here: https://github.com/graphhopper/directions-api-java-client/commit/6a369e08fed618c35c5609af80acaae570339211

Can you please try again if this is still an issue, see e.g. the entry for distribution management: https://github.com/graphhopper/directions-api-java-client/commit/6a369e08fed618c35c5609af80acaae570339211#diff-600376dffeb79835ede4a0b285078036R126

**Comment by boldtrn** [comment]
I just copied it from here: https://github.com/graphhopper/graphhopper/blob/master/docs/core/quickstart-from-source.md

**Comment by karussell** [comment]
And is the latest master working for you (without the snapshot addition)?

**Comment by devemux86** [comment]
@karussell the entry you mentioned above is needed only for Maven snapshot publishing?

In `map-matching` we have the snapshot repository for publishing [here](https://github.com/graphhopper/map-matching/blob/master/pom.xml#L137) in central pom and the corresponding for dependencies [here](https://github.com/graphhopper/map-matching/blob/master/matching-core/pom.xml#L99) in core pom.

**Comment by karussell** [comment]
@devemux86 thanks, indeed the snippet in map-matching-core should not be necessary. Have removed it: https://github.com/graphhopper/map-matching/commit/bbefddb620bb8eb0b2a9603fc822aaa6db2a7fba same for this repo: https://github.com/graphhopper/directions-api-java-client/commit/2ff99e5c4dbf53e0586c5f33d0e2519bca01a572

But what I meant was the parent pom of this repo where an additional entry should no longer be necessary, see this line: https://github.com/graphhopper/directions-api-java-client/blob/master/pom.xml#L129

**Comment by devemux86** [comment]
In parent pom no, but like we have the dependencies snapshot repository declared in map-matching core and in graphhopper/android sample, shouldn't we have it also in directions modules?

**Comment by devemux86** [comment]
Sorry just seen that you removed from map-matching.

**Comment by boldtrn** [comment]
Thanks for your comments, I switched to the new URL. This seems to fetch the graphhopper-core correctly for me.

**Comment by karussell** [comment]
As I fixed this already in this PR:

> But what I meant was the parent pom of this repo where an additional entry should no longer be necessary, see this line: https://github.com/graphhopper/directions-api-java-client/blob/master/pom.xml#L129

can we close this or is something else missing?

**Comment by boldtrn** [comment]
> can we close this or is something else missing?

Mhm, maybe I am doing something wrong, but when I use the current master and run: `mvn -Dgraphhopper.key=MY_KEY clean test verify`

I get the following exception:

```
[ERROR] Failed to execute goal on project directions-api-java-client: Could not resolve dependencies for project com.graphhopper:directions-api-java-client:jar:0.8-SNAPSHOT: Could not find artifact com.graphhopper:graphhopper-core:jar:0.8-SNAPSHOT -> [Help 1]
```

But when I add my changes of this PR, it works. In order to test it you need to delete graphhopper-core from your local m2 repository, typically located at `~/.m2/repository/com`.

**Comment by karussell** [comment]
Did you update to the latest master? As similar lines are already in the pom.xml: https://github.com/graphhopper/directions-api-java-client/blob/master/pom.xml#L126

**Comment by karussell** [comment]
I removed the local cache and indeed there is something wrong...

**Comment by karussell** [comment]
You are right this snippet is **additionally** required: http://stackoverflow.com/q/35317118/194609

**Comment by devemux86** [comment]
See also my [post](https://github.com/graphhopper/directions-api-java-client/pull/21#issuecomment-246185880) above.
Publishing repository declaration is different than that for dependencies.

**Comment by devemux86** [comment]
@karussell the addition should be done in map-matching too?

**Comment by karussell** [comment]
> @karussell the addition should be done in map-matching too?

Yes. Or/plus I'm thinking about merging GH and map matching then it would not be necessary.

**Comment by devemux86** [comment]
> Or/plus I'm thinking about merging GH and map matching then it would not be necessary.

As a module under GH? (worrying about dependencies)
And what about its Git history?

**Comment by karussell** [comment]
> As a module under GH? (worrying about dependencies)

Yes, sure just as two additional modules. Dependencies would remain. See my thoughts on why this will be necessary: https://github.com/graphhopper/graphhopper/pull/781

Also this makes other stuff easier.

> And what about its Git history?

They would be lost, I think

**Pull request merged**
